language: c

notifications:
  email: false

jobs:
  include:
  - stage: build
    os: linux
    arch: amd64
    compiler: clang
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - clang hellonoise.c -o hellonoise -lm -mavx -mavx2 -fopenmp=libiomp5
      - ./hellonoise
      - clang benchmarks.c -o benchmarks -lm -mavx -mavx2 -fopenmp=libiomp5 -O3
      - ./benchmarks

  - stage: build
    os: linux
    arch: amd64
    compiler: gcc
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - gcc hellonoise.c -o hellonoise -lm -mavx -mavx2 -fopenmp
      - ./hellonoise
      - gcc benchmarks.c -o benchmarks -lm -mavx -mavx2 -fopenmp -O3
      - ./benchmarks

  - stage: build
    os: linux
    arch: arm64
    compiler: clang
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - clang hellonoise.c -o hellonoise -lm -mavx -mavx2 -fopenmp=libiomp5
      - ./hellonoise
      - clang benchmarks.c -o benchmarks -lm -mavx -mavx2 -fopenmp=libiomp5 -O3
      - ./benchmarks

  - stage: build
    os: linux
    arch: arm64
    compiler: gcc
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - gcc hellonoise.c -o hellonoise -lm -mavx -mavx2 -fopenmp
      - ./hellonoise
      - gcc benchmarks.c -o benchmarks -lm -mavx -mavx2 -fopenmp -O3
      - ./benchmarks

  - stage: build
    os: osx
    compiler: clang
    before_install:
      - brew update
      - brew install llvm libomp
    sudo: true
    script:
      - cd examples
      - /usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib hellonoise.c -o hellonoise -lm -mavx -mavx2
      - ./hellonoise
      - /usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib benchmarks.c -o benchmarks -lm -mavx -mavx2 -O3
      - ./benchmarks
