language: c
sudo: false
compiler:
  - clang
  - gcc
script:
  - cd examples
  - clang hellonoise.c -o hellonoise -lm -mavx2 -fopenmp=libiomp5
  - ./hellonoise
  - clang benchmarks.c -o benchmarks -lm -mavx2 -fopenmp=libiomp5
  - ./benchmarks