language: c

notifications:
  email: false

jobs:
  include:
  - stage: build
    os: linux
    arch: amd64
    compiler: clang
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - clang hellonoise.c -o hellonoise -lm -mavx2 -fopenmp=libiomp5
      - ./hellonoise
      - clang benchmarks.c -o benchmarks -lm -mavx2 -fopenmp=libiomp5
      - ./benchmarks

  - stage: build
    os: linux
    arch: amd64
    compiler: gcc
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - gcc hellonoise.c -o hellonoise -lm -mavx2 -fopenmp
      - ./hellonoise
      - gcc benchmarks.c -o benchmarks -lm -mavx2 -fopenmp
      - ./benchmarks

  - stage: build
    os: linux
    arch: arm64
    compiler: clang
    sudo: true
    before_install: sudo apt-get install libomp-dev
    script:
      - cd examples
      - clang hellonoise.c -o hellonoise -lm -mavx2 -fopenmp=libiomp5
      - ./hellonoise
      - clang benchmarks.c -o benchmarks -lm -mavx2 -fopenmp=libiomp5
      - ./benchmarks

  - stage: build
    os: osx
    compiler: clang
    sudo: true
    script:
      - cd examples
      - clang hellonoise.c -o hellonoise -lm -mavx2 -fopenmp=libiomp5
      - ./hellonoise
      - clang benchmarks.c -o benchmarks -lm -mavx2 -fopenmp=libiomp5
      - ./benchmarks
