language: c
os:
  - linux
compiler:
  - clang
  - gcc
sudo: true
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libomp-dev; fi
script:
  - cd examples
  - $TRAVIS_COMPILER hellonoise.c -o hellonoise -lm -mavx2 -fopenmp=libiomp5
  - ./hellonoise
  - $TRAVIS_COMPILER benchmarks.c -o benchmarks -lm -mavx2 -fopenmp=libiomp5
  - ./benchmarks