
name: CI
on: [push]
jobs:
  build-osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install libomp
    - name: Build all
      run: mkdir examples/build && cs examples/build && cmake ../../ && make
    - name: Run hellonoise
      run: ./examples/build/Debug/hellonoise
    - name: Run benchmarks
      run: ./examples/build/Debug/benchmarks
      
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all
      run: 'cmd.exe /c "`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && mkdir examples\build && cd examples\build && cmake -G `"Visual Studio 16 2019`" ../../ && MSBuild Benchmarks.sln"'
    - name: Run hellonoise
      run: examples\build\Debug\hellonoise.exe
    - name: Run benchmarks
      run: examples\build\Debug\benchmarks.exe
      
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all
      run: 'mkdir examples/build && cs examples/build && cmake -G "clang" ../../ && make'
    - name: Run hellonoise
      run: ./examples/hellonoise
    - name: Run benchmarks
      run: ./examples/benchmarks
      
  build-ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all
      run: 'mkdir examples/build && cs examples/build && cmake -G "gcc" ../../ && make'
    - name: Run hellonoise
      run: ./examples/build/Debug/hellonoise
    - name: Run benchmarks
      run: ./examples/build/Debug/benchmarks
      
