
name: CI
on: [push]
jobs:
   
  build-osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install libomp
    - name: Build hellonoise
      run: clang examples/hellonoise.c -o examples/hellonoise -lm -Xpreprocessor -fopenmp -lomp -mavx -mavx2 && ./examples/hellonoise
    - name: Build benchmarks
      run: clang examples/benchmarks.c -o examples/benchmarks -lm -Xpreprocessor -fopenmp -lomp -mavx -mavx2 && ./examples/benchmarks
    
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build hellonoise
      run: clang examples/hellonoise.c -o examples/hellonoise -lm -fopenmp=libiomp5 -mavx -mavx2 && ./examples/hellonoise
    - name: Build benchmarks
      run: clang examples/benchmarks.c -o examples/benchmarks -lm -fopenmp=libiomp5 -mavx -mavx2 && ./examples/benchmarks
